name: CI
on: [push, pull_request]

jobs:
  build-linux-ghc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: submodule
        run: git submodule update --init --recursive
      - name: build
        run: make
